<?php

namespace AppBundle\Repository;

/**
 * cinema_hallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cinema_hallRepository extends \Doctrine\ORM\EntityRepository
{
}
