<?php

namespace AppBundle\Repository;

/**
 * Cinema_hall_has_MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cinema_hall_has_MovieRepository extends \Doctrine\ORM\EntityRepository
{
}
