<?php

namespace AppBundle\Repository;

/**
 * MovieImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
