<?php

namespace AppBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByCinema($cinemaId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM AppBundle:Movie m WHERE m.id IN (
                        SELECT (cm.movieId) FROM AppBundle:Cinema_hall_has_Movie cm WHERE cm.cinemaHallId IN (
                            SELECT ch.id FROM AppBundle:Cinema_hall ch WHERE ch.cinemaId = :id
                        )
                    )'
            )->setParameter('id', $cinemaId);
        return $query->getResult();
    }
}
