<?php

namespace AppBundle\Repository;

/**
 * Ticket_soldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ticket_soldRepository extends \Doctrine\ORM\EntityRepository
{
}
